name: Handle New Comments

on:
  issue_comment:
    types: [created, edited]  # Trigger workflow when a comment is created or modified

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
    
      - name: Install Python dependencies
        shell: bash
        run: python -m pip install -r action-requirements.txt
      
      - name: Check if comment is on the chat issue
        id: check_issue
        run: |
          if [ "${{ github.event.issue.number }}" -eq "1" ]; then
            exit 0
          else
            exit 1
          fi

      - name: Respond to comment
        if: ${{ success() }}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          python main.py

      - name: Commit Changes
        id: "add-and-commit"
        uses: EndBug/add-and-commit@v9
        with:
          message: "docs(svgs): Chat updated"
          author_name: "GitHub Actions"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"